// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gamedata.proto

package gamedata

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Prefab int32

const (
	Prefab_Invalid Prefab = 0
	Prefab_DemoBox Prefab = 1
)

var Prefab_name = map[int32]string{
	0: "Invalid",
	1: "DemoBox",
}

var Prefab_value = map[string]int32{
	"Invalid": 0,
	"DemoBox": 1,
}

func (x Prefab) String() string {
	return proto.EnumName(Prefab_name, int32(x))
}

func (Prefab) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{0}
}

type Force_ForceMode int32

const (
	Force_Force   Force_ForceMode = 0
	Force_Impulse Force_ForceMode = 1
)

var Force_ForceMode_name = map[int32]string{
	0: "Force",
	1: "Impulse",
}

var Force_ForceMode_value = map[string]int32{
	"Force":   0,
	"Impulse": 1,
}

func (x Force_ForceMode) String() string {
	return proto.EnumName(Force_ForceMode_name, int32(x))
}

func (Force_ForceMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{13, 0}
}

type Header_OpCode int32

const (
	Header_Invalid Header_OpCode = 0
	// (A.1) client informs game server of successful connection to
	// coordinator
	Header_ClientOnline      Header_OpCode = 100
	Header_GameServerOnline  Header_OpCode = 101
	Header_GameServerStart   Header_OpCode = 102
	Header_ClientGameRequest Header_OpCode = 200
	Header_ClientGameCancel  Header_OpCode = 201
	Header_ClientGameFound   Header_OpCode = 202
	// (A.5) (FixedUpdate) sim server sends existing client game object's
	// delta to game server
	// (B.3) (FixedUpdate) game server sends existing game object's delta to
	// all clients
	Header_ClientJoin      Header_OpCode = 300
	Header_SimulationState Header_OpCode = 301
	// Object creation
	Header_GameObject Header_OpCode = 400
	Header_Rigidbody  Header_OpCode = 401
	// Object updates
	Header_Position Header_OpCode = 500
	Header_Rotation Header_OpCode = 501
	Header_Scale    Header_OpCode = 502
	Header_Velocity Header_OpCode = 503
	Header_Force    Header_OpCode = 504
)

var Header_OpCode_name = map[int32]string{
	0:   "Invalid",
	100: "ClientOnline",
	101: "GameServerOnline",
	102: "GameServerStart",
	200: "ClientGameRequest",
	201: "ClientGameCancel",
	202: "ClientGameFound",
	300: "ClientJoin",
	301: "SimulationState",
	400: "GameObject",
	401: "Rigidbody",
	500: "Position",
	501: "Rotation",
	502: "Scale",
	503: "Velocity",
	504: "Force",
}

var Header_OpCode_value = map[string]int32{
	"Invalid":           0,
	"ClientOnline":      100,
	"GameServerOnline":  101,
	"GameServerStart":   102,
	"ClientGameRequest": 200,
	"ClientGameCancel":  201,
	"ClientGameFound":   202,
	"ClientJoin":        300,
	"SimulationState":   301,
	"GameObject":        400,
	"Rigidbody":         401,
	"Position":          500,
	"Rotation":          501,
	"Scale":             502,
	"Velocity":          503,
	"Force":             504,
}

func (x Header_OpCode) String() string {
	return proto.EnumName(Header_OpCode_name, int32(x))
}

func (Header_OpCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{15, 0}
}

type Packet struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data                 *any.Any `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{0}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Packet) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type ClientJoin struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientJoin) Reset()         { *m = ClientJoin{} }
func (m *ClientJoin) String() string { return proto.CompactTextString(m) }
func (*ClientJoin) ProtoMessage()    {}
func (*ClientJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{1}
}

func (m *ClientJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientJoin.Unmarshal(m, b)
}
func (m *ClientJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientJoin.Marshal(b, m, deterministic)
}
func (m *ClientJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientJoin.Merge(m, src)
}
func (m *ClientJoin) XXX_Size() int {
	return xxx_messageInfo_ClientJoin.Size(m)
}
func (m *ClientJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientJoin.DiscardUnknown(m)
}

var xxx_messageInfo_ClientJoin proto.InternalMessageInfo

type ClientConnection struct {
	// id of client to accept packets from
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// address of the client packets should be coming from
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientConnection) Reset()         { *m = ClientConnection{} }
func (m *ClientConnection) String() string { return proto.CompactTextString(m) }
func (*ClientConnection) ProtoMessage()    {}
func (*ClientConnection) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{2}
}

func (m *ClientConnection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientConnection.Unmarshal(m, b)
}
func (m *ClientConnection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientConnection.Marshal(b, m, deterministic)
}
func (m *ClientConnection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientConnection.Merge(m, src)
}
func (m *ClientConnection) XXX_Size() int {
	return xxx_messageInfo_ClientConnection.Size(m)
}
func (m *ClientConnection) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientConnection.DiscardUnknown(m)
}

var xxx_messageInfo_ClientConnection proto.InternalMessageInfo

func (m *ClientConnection) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ClientConnection) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ClientOnline struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientOnline) Reset()         { *m = ClientOnline{} }
func (m *ClientOnline) String() string { return proto.CompactTextString(m) }
func (*ClientOnline) ProtoMessage()    {}
func (*ClientOnline) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{3}
}

func (m *ClientOnline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientOnline.Unmarshal(m, b)
}
func (m *ClientOnline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientOnline.Marshal(b, m, deterministic)
}
func (m *ClientOnline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientOnline.Merge(m, src)
}
func (m *ClientOnline) XXX_Size() int {
	return xxx_messageInfo_ClientOnline.Size(m)
}
func (m *ClientOnline) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientOnline.DiscardUnknown(m)
}

var xxx_messageInfo_ClientOnline proto.InternalMessageInfo

func (m *ClientOnline) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GameServerOnline struct {
	Secret               string   `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Region               string   `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Capacity             int32    `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameServerOnline) Reset()         { *m = GameServerOnline{} }
func (m *GameServerOnline) String() string { return proto.CompactTextString(m) }
func (*GameServerOnline) ProtoMessage()    {}
func (*GameServerOnline) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{4}
}

func (m *GameServerOnline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameServerOnline.Unmarshal(m, b)
}
func (m *GameServerOnline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameServerOnline.Marshal(b, m, deterministic)
}
func (m *GameServerOnline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameServerOnline.Merge(m, src)
}
func (m *GameServerOnline) XXX_Size() int {
	return xxx_messageInfo_GameServerOnline.Size(m)
}
func (m *GameServerOnline) XXX_DiscardUnknown() {
	xxx_messageInfo_GameServerOnline.DiscardUnknown(m)
}

var xxx_messageInfo_GameServerOnline proto.InternalMessageInfo

func (m *GameServerOnline) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *GameServerOnline) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *GameServerOnline) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

type GameServerStart struct {
	ID                   string              `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Clients              []*ClientConnection `protobuf:"bytes,2,rep,name=clients,proto3" json:"clients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GameServerStart) Reset()         { *m = GameServerStart{} }
func (m *GameServerStart) String() string { return proto.CompactTextString(m) }
func (*GameServerStart) ProtoMessage()    {}
func (*GameServerStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{5}
}

func (m *GameServerStart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameServerStart.Unmarshal(m, b)
}
func (m *GameServerStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameServerStart.Marshal(b, m, deterministic)
}
func (m *GameServerStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameServerStart.Merge(m, src)
}
func (m *GameServerStart) XXX_Size() int {
	return xxx_messageInfo_GameServerStart.Size(m)
}
func (m *GameServerStart) XXX_DiscardUnknown() {
	xxx_messageInfo_GameServerStart.DiscardUnknown(m)
}

var xxx_messageInfo_GameServerStart proto.InternalMessageInfo

func (m *GameServerStart) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *GameServerStart) GetClients() []*ClientConnection {
	if m != nil {
		return m.Clients
	}
	return nil
}

type ClientGameFound struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientGameFound) Reset()         { *m = ClientGameFound{} }
func (m *ClientGameFound) String() string { return proto.CompactTextString(m) }
func (*ClientGameFound) ProtoMessage()    {}
func (*ClientGameFound) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{6}
}

func (m *ClientGameFound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientGameFound.Unmarshal(m, b)
}
func (m *ClientGameFound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientGameFound.Marshal(b, m, deterministic)
}
func (m *ClientGameFound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientGameFound.Merge(m, src)
}
func (m *ClientGameFound) XXX_Size() int {
	return xxx_messageInfo_ClientGameFound.Size(m)
}
func (m *ClientGameFound) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientGameFound.DiscardUnknown(m)
}

var xxx_messageInfo_ClientGameFound proto.InternalMessageInfo

func (m *ClientGameFound) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ClientGameRequest struct {
	Region               string   `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientGameRequest) Reset()         { *m = ClientGameRequest{} }
func (m *ClientGameRequest) String() string { return proto.CompactTextString(m) }
func (*ClientGameRequest) ProtoMessage()    {}
func (*ClientGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{7}
}

func (m *ClientGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientGameRequest.Unmarshal(m, b)
}
func (m *ClientGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientGameRequest.Marshal(b, m, deterministic)
}
func (m *ClientGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientGameRequest.Merge(m, src)
}
func (m *ClientGameRequest) XXX_Size() int {
	return xxx_messageInfo_ClientGameRequest.Size(m)
}
func (m *ClientGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientGameRequest proto.InternalMessageInfo

func (m *ClientGameRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type ClientGameCancel struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientGameCancel) Reset()         { *m = ClientGameCancel{} }
func (m *ClientGameCancel) String() string { return proto.CompactTextString(m) }
func (*ClientGameCancel) ProtoMessage()    {}
func (*ClientGameCancel) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{8}
}

func (m *ClientGameCancel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientGameCancel.Unmarshal(m, b)
}
func (m *ClientGameCancel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientGameCancel.Marshal(b, m, deterministic)
}
func (m *ClientGameCancel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientGameCancel.Merge(m, src)
}
func (m *ClientGameCancel) XXX_Size() int {
	return xxx_messageInfo_ClientGameCancel.Size(m)
}
func (m *ClientGameCancel) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientGameCancel.DiscardUnknown(m)
}

var xxx_messageInfo_ClientGameCancel proto.InternalMessageInfo

// message NewClientGameObject {
//    int32 ID = 1;
//    Prefab prefab = 2;
//}
//
// message NewGameObject {
//    int32 ID = 1;
//    Prefab prefab = 2;
//}
//
type SimulationState struct {
	Transforms           []*GameObject `protobuf:"bytes,1,rep,name=transforms,proto3" json:"transforms,omitempty"`
	RigidBodies          []*Rigidbody  `protobuf:"bytes,2,rep,name=rigidBodies,proto3" json:"rigidBodies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SimulationState) Reset()         { *m = SimulationState{} }
func (m *SimulationState) String() string { return proto.CompactTextString(m) }
func (*SimulationState) ProtoMessage()    {}
func (*SimulationState) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{9}
}

func (m *SimulationState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimulationState.Unmarshal(m, b)
}
func (m *SimulationState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimulationState.Marshal(b, m, deterministic)
}
func (m *SimulationState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimulationState.Merge(m, src)
}
func (m *SimulationState) XXX_Size() int {
	return xxx_messageInfo_SimulationState.Size(m)
}
func (m *SimulationState) XXX_DiscardUnknown() {
	xxx_messageInfo_SimulationState.DiscardUnknown(m)
}

var xxx_messageInfo_SimulationState proto.InternalMessageInfo

func (m *SimulationState) GetTransforms() []*GameObject {
	if m != nil {
		return m.Transforms
	}
	return nil
}

func (m *SimulationState) GetRigidBodies() []*Rigidbody {
	if m != nil {
		return m.RigidBodies
	}
	return nil
}

type GameObject struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Prefab               Prefab   `protobuf:"varint,2,opt,name=Prefab,proto3,enum=gamedata.Prefab" json:"Prefab,omitempty"`
	Position             *Vector2 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Rotation             float32  `protobuf:"fixed32,4,opt,name=rotation,proto3" json:"rotation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameObject) Reset()         { *m = GameObject{} }
func (m *GameObject) String() string { return proto.CompactTextString(m) }
func (*GameObject) ProtoMessage()    {}
func (*GameObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{10}
}

func (m *GameObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameObject.Unmarshal(m, b)
}
func (m *GameObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameObject.Marshal(b, m, deterministic)
}
func (m *GameObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameObject.Merge(m, src)
}
func (m *GameObject) XXX_Size() int {
	return xxx_messageInfo_GameObject.Size(m)
}
func (m *GameObject) XXX_DiscardUnknown() {
	xxx_messageInfo_GameObject.DiscardUnknown(m)
}

var xxx_messageInfo_GameObject proto.InternalMessageInfo

func (m *GameObject) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *GameObject) GetPrefab() Prefab {
	if m != nil {
		return m.Prefab
	}
	return Prefab_Invalid
}

func (m *GameObject) GetPosition() *Vector2 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *GameObject) GetRotation() float32 {
	if m != nil {
		return m.Rotation
	}
	return 0
}

type Rigidbody struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Prefab               Prefab   `protobuf:"varint,2,opt,name=Prefab,proto3,enum=gamedata.Prefab" json:"Prefab,omitempty"`
	Position             *Vector2 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Rotation             float32  `protobuf:"fixed32,4,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Velocity             *Vector2 `protobuf:"bytes,5,opt,name=velocity,proto3" json:"velocity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rigidbody) Reset()         { *m = Rigidbody{} }
func (m *Rigidbody) String() string { return proto.CompactTextString(m) }
func (*Rigidbody) ProtoMessage()    {}
func (*Rigidbody) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{11}
}

func (m *Rigidbody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rigidbody.Unmarshal(m, b)
}
func (m *Rigidbody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rigidbody.Marshal(b, m, deterministic)
}
func (m *Rigidbody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rigidbody.Merge(m, src)
}
func (m *Rigidbody) XXX_Size() int {
	return xxx_messageInfo_Rigidbody.Size(m)
}
func (m *Rigidbody) XXX_DiscardUnknown() {
	xxx_messageInfo_Rigidbody.DiscardUnknown(m)
}

var xxx_messageInfo_Rigidbody proto.InternalMessageInfo

func (m *Rigidbody) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Rigidbody) GetPrefab() Prefab {
	if m != nil {
		return m.Prefab
	}
	return Prefab_Invalid
}

func (m *Rigidbody) GetPosition() *Vector2 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Rigidbody) GetRotation() float32 {
	if m != nil {
		return m.Rotation
	}
	return 0
}

func (m *Rigidbody) GetVelocity() *Vector2 {
	if m != nil {
		return m.Velocity
	}
	return nil
}

type Velocity struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	X                    float32  `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Velocity) Reset()         { *m = Velocity{} }
func (m *Velocity) String() string { return proto.CompactTextString(m) }
func (*Velocity) ProtoMessage()    {}
func (*Velocity) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{12}
}

func (m *Velocity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Velocity.Unmarshal(m, b)
}
func (m *Velocity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Velocity.Marshal(b, m, deterministic)
}
func (m *Velocity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Velocity.Merge(m, src)
}
func (m *Velocity) XXX_Size() int {
	return xxx_messageInfo_Velocity.Size(m)
}
func (m *Velocity) XXX_DiscardUnknown() {
	xxx_messageInfo_Velocity.DiscardUnknown(m)
}

var xxx_messageInfo_Velocity proto.InternalMessageInfo

func (m *Velocity) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Velocity) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Velocity) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Force struct {
	ID                   string          `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	X                    float32         `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32         `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	ForceMode            Force_ForceMode `protobuf:"varint,4,opt,name=forceMode,proto3,enum=gamedata.Force_ForceMode" json:"forceMode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Force) Reset()         { *m = Force{} }
func (m *Force) String() string { return proto.CompactTextString(m) }
func (*Force) ProtoMessage()    {}
func (*Force) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{13}
}

func (m *Force) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Force.Unmarshal(m, b)
}
func (m *Force) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Force.Marshal(b, m, deterministic)
}
func (m *Force) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Force.Merge(m, src)
}
func (m *Force) XXX_Size() int {
	return xxx_messageInfo_Force.Size(m)
}
func (m *Force) XXX_DiscardUnknown() {
	xxx_messageInfo_Force.DiscardUnknown(m)
}

var xxx_messageInfo_Force proto.InternalMessageInfo

func (m *Force) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Force) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Force) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Force) GetForceMode() Force_ForceMode {
	if m != nil {
		return m.ForceMode
	}
	return Force_Force
}

type Vector2 struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vector2) Reset()         { *m = Vector2{} }
func (m *Vector2) String() string { return proto.CompactTextString(m) }
func (*Vector2) ProtoMessage()    {}
func (*Vector2) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{14}
}

func (m *Vector2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector2.Unmarshal(m, b)
}
func (m *Vector2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector2.Marshal(b, m, deterministic)
}
func (m *Vector2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector2.Merge(m, src)
}
func (m *Vector2) XXX_Size() int {
	return xxx_messageInfo_Vector2.Size(m)
}
func (m *Vector2) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector2.DiscardUnknown(m)
}

var xxx_messageInfo_Vector2 proto.InternalMessageInfo

func (m *Vector2) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vector2) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Header struct {
	// this is a connection id that expires once the coordinator connection is
	// lost
	Cid                  string        `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	OpCode               Header_OpCode `protobuf:"varint,2,opt,name=opCode,proto3,enum=gamedata.Header_OpCode" json:"opCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{15}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *Header) GetOpCode() Header_OpCode {
	if m != nil {
		return m.OpCode
	}
	return Header_Invalid
}

func init() {
	proto.RegisterEnum("gamedata.Prefab", Prefab_name, Prefab_value)
	proto.RegisterEnum("gamedata.Force_ForceMode", Force_ForceMode_name, Force_ForceMode_value)
	proto.RegisterEnum("gamedata.Header_OpCode", Header_OpCode_name, Header_OpCode_value)
	proto.RegisterType((*Packet)(nil), "gamedata.Packet")
	proto.RegisterType((*ClientJoin)(nil), "gamedata.ClientJoin")
	proto.RegisterType((*ClientConnection)(nil), "gamedata.ClientConnection")
	proto.RegisterType((*ClientOnline)(nil), "gamedata.ClientOnline")
	proto.RegisterType((*GameServerOnline)(nil), "gamedata.GameServerOnline")
	proto.RegisterType((*GameServerStart)(nil), "gamedata.GameServerStart")
	proto.RegisterType((*ClientGameFound)(nil), "gamedata.ClientGameFound")
	proto.RegisterType((*ClientGameRequest)(nil), "gamedata.ClientGameRequest")
	proto.RegisterType((*ClientGameCancel)(nil), "gamedata.ClientGameCancel")
	proto.RegisterType((*SimulationState)(nil), "gamedata.SimulationState")
	proto.RegisterType((*GameObject)(nil), "gamedata.GameObject")
	proto.RegisterType((*Rigidbody)(nil), "gamedata.Rigidbody")
	proto.RegisterType((*Velocity)(nil), "gamedata.Velocity")
	proto.RegisterType((*Force)(nil), "gamedata.Force")
	proto.RegisterType((*Vector2)(nil), "gamedata.Vector2")
	proto.RegisterType((*Header)(nil), "gamedata.Header")
}

func init() { proto.RegisterFile("gamedata.proto", fileDescriptor_38d51a89ffb18ac9) }

var fileDescriptor_38d51a89ffb18ac9 = []byte{
	// 750 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0xee, 0x38, 0x8d, 0x93, 0x9c, 0xf4, 0x26, 0xd3, 0x69, 0x6e, 0x6f, 0xda, 0x55, 0xef, 0x20,
	0xa4, 0x08, 0x44, 0x2a, 0x85, 0x02, 0x1b, 0x36, 0x34, 0x55, 0xa1, 0x48, 0xa8, 0xd5, 0x44, 0x2a,
	0x1b, 0x84, 0x34, 0xb1, 0x4f, 0x82, 0xc1, 0xf1, 0x04, 0xdb, 0xa9, 0x9a, 0x0d, 0xcf, 0x40, 0xdf,
	0x81, 0x25, 0x3c, 0x03, 0x5b, 0xe0, 0x71, 0x10, 0x7f, 0x4b, 0x34, 0x63, 0x3b, 0x4e, 0x13, 0x58,
	0xb0, 0x63, 0x13, 0xf9, 0x9c, 0xf3, 0xcd, 0x37, 0xdf, 0x99, 0xf3, 0x13, 0xa8, 0x0d, 0xe5, 0x08,
	0x5d, 0x19, 0xcb, 0xf6, 0x38, 0x54, 0xb1, 0x62, 0xe5, 0xcc, 0xde, 0xde, 0x1a, 0x2a, 0x35, 0xf4,
	0x71, 0xd7, 0xf8, 0xfb, 0x93, 0xc1, 0xae, 0x0c, 0xa6, 0x09, 0x88, 0x3f, 0x01, 0xfb, 0x44, 0x3a,
	0x2f, 0x30, 0x66, 0x2d, 0xb0, 0x9f, 0xa1, 0x74, 0x31, 0x6c, 0x92, 0x1d, 0xd2, 0xaa, 0x76, 0x68,
	0x7b, 0xc6, 0xf7, 0xc0, 0xf8, 0x45, 0x1a, 0x67, 0x2d, 0x58, 0xd5, 0xee, 0xa6, 0x65, 0x70, 0x8d,
	0x76, 0xc2, 0xde, 0xce, 0xd8, 0xdb, 0xf7, 0x82, 0xa9, 0x30, 0x08, 0xbe, 0x06, 0xd0, 0xf5, 0x3d,
	0x0c, 0xe2, 0x87, 0xca, 0x0b, 0xf8, 0x5d, 0xa0, 0x89, 0xd5, 0x55, 0x41, 0x80, 0x4e, 0xec, 0xa9,
	0x80, 0xd5, 0xc0, 0x3a, 0x3a, 0x30, 0x37, 0x56, 0x84, 0x75, 0x74, 0xc0, 0x9a, 0x50, 0x92, 0xae,
	0x1b, 0x62, 0x14, 0x19, 0xfa, 0x8a, 0xc8, 0x4c, 0xce, 0x61, 0x2d, 0x39, 0x7d, 0x1c, 0xf8, 0x5e,
	0x80, 0x8c, 0xc1, 0x6a, 0x20, 0x47, 0x98, 0x9e, 0x35, 0xdf, 0xfc, 0x29, 0xd0, 0xfb, 0x72, 0x84,
	0x3d, 0x0c, 0xcf, 0x30, 0x4c, 0x71, 0x9b, 0x60, 0x47, 0xe8, 0x84, 0x18, 0xa7, 0xc8, 0xd4, 0xd2,
	0xfe, 0x10, 0x87, 0x9e, 0x0a, 0xd2, 0x8b, 0x52, 0x8b, 0x6d, 0x43, 0xd9, 0x91, 0x63, 0xe9, 0x78,
	0xf1, 0xb4, 0x59, 0xd8, 0x21, 0xad, 0xa2, 0x98, 0xd9, 0xfc, 0x31, 0xd4, 0x73, 0xfe, 0x5e, 0x2c,
	0xc3, 0x78, 0x29, 0x81, 0x3d, 0x28, 0x39, 0x46, 0xa6, 0x4e, 0xa0, 0xd0, 0xaa, 0x76, 0xb6, 0xf3,
	0x77, 0x5c, 0xcc, 0x5e, 0x64, 0x50, 0xfe, 0x3f, 0xd4, 0x93, 0xa0, 0xa6, 0x3f, 0x54, 0x93, 0xc0,
	0x5d, 0x24, 0xe6, 0xd7, 0x61, 0x3d, 0x87, 0x08, 0x7c, 0x39, 0xc1, 0x68, 0x3e, 0x09, 0x32, 0x9f,
	0x04, 0x67, 0xd9, 0x53, 0x6b, 0x70, 0x57, 0x06, 0x0e, 0xfa, 0xfc, 0x15, 0xd4, 0x7b, 0xde, 0x68,
	0xe2, 0x4b, 0x7d, 0x75, 0x2f, 0x96, 0x31, 0xb2, 0x3d, 0x80, 0x38, 0x94, 0x41, 0x34, 0x50, 0xe1,
	0x28, 0x6a, 0x12, 0xa3, 0xb7, 0x91, 0xeb, 0xd5, 0x87, 0x8f, 0xfb, 0xcf, 0xd1, 0x89, 0xc5, 0x1c,
	0x8e, 0xdd, 0x82, 0x6a, 0xe8, 0x0d, 0x3d, 0x77, 0x5f, 0xb9, 0x1e, 0x66, 0x69, 0x6e, 0xe4, 0xc7,
	0x84, 0x0e, 0xf6, 0x95, 0x3b, 0x15, 0xf3, 0x38, 0x7e, 0x41, 0x00, 0x72, 0xc6, 0xa5, 0x87, 0x6b,
	0x81, 0x7d, 0x12, 0xe2, 0x40, 0xf6, 0x4d, 0x3d, 0x6a, 0xf3, 0xfd, 0x97, 0xf8, 0x45, 0x1a, 0x67,
	0x37, 0xa0, 0x3c, 0x56, 0x91, 0xa7, 0xd3, 0x30, 0x15, 0xaa, 0x76, 0xd6, 0x73, 0xec, 0x29, 0x3a,
	0xb1, 0x0a, 0x3b, 0x62, 0x06, 0xd1, 0x05, 0x0d, 0x55, 0x6c, 0xb2, 0x6e, 0xae, 0xee, 0x90, 0x96,
	0x25, 0x66, 0x36, 0x7f, 0x4f, 0xa0, 0x32, 0x93, 0xfb, 0x57, 0x48, 0xd2, 0x54, 0x67, 0xe8, 0x2b,
	0xd3, 0x7f, 0xc5, 0xdf, 0x52, 0x65, 0x10, 0x7e, 0x1b, 0xca, 0xa7, 0xe9, 0xf7, 0x92, 0xfe, 0x35,
	0x20, 0xe7, 0x46, 0xba, 0x25, 0xc8, 0xb9, 0xb6, 0x92, 0x8e, 0xb6, 0x04, 0x99, 0xea, 0x6a, 0x14,
	0x0f, 0x55, 0xe8, 0xe0, 0x9f, 0x9c, 0x62, 0x77, 0xa0, 0x32, 0xd0, 0x87, 0x1e, 0x29, 0x17, 0x8d,
	0xf2, 0x5a, 0x67, 0x2b, 0x57, 0x67, 0xf8, 0x92, 0x5f, 0x0d, 0x10, 0x39, 0x96, 0x5f, 0x81, 0xca,
	0xcc, 0xcf, 0x2a, 0xe9, 0xd5, 0x74, 0x85, 0x55, 0xa1, 0x74, 0x34, 0x1a, 0x4f, 0xfc, 0x08, 0x29,
	0xe1, 0x57, 0xa1, 0x94, 0x26, 0x98, 0x88, 0x20, 0x97, 0x44, 0x58, 0x99, 0xf4, 0xcf, 0x16, 0xd8,
	0xc9, 0x4a, 0x62, 0x14, 0x0a, 0x8e, 0xe7, 0xa6, 0xe2, 0xf5, 0x27, 0xdb, 0x05, 0x5b, 0x8d, 0xbb,
	0x5a, 0x5e, 0x52, 0xb3, 0xff, 0x16, 0xd7, 0x58, 0xfb, 0xd8, 0x84, 0x45, 0x0a, 0xe3, 0x6f, 0x2c,
	0xb0, 0x13, 0x97, 0x11, 0x13, 0x9c, 0x49, 0xdf, 0x73, 0xe9, 0x0a, 0xa3, 0x97, 0xf7, 0x0d, 0x75,
	0x59, 0x63, 0x79, 0xbb, 0x50, 0x64, 0x1b, 0x4b, 0x3b, 0x81, 0x0e, 0xd8, 0xe6, 0x2f, 0x86, 0x95,
	0x7e, 0x20, 0xec, 0xdf, 0xe5, 0xb9, 0xa4, 0x1f, 0x09, 0x6b, 0x2c, 0x8d, 0x3f, 0xfd, 0x44, 0x58,
	0x7d, 0x7e, 0x7b, 0xd2, 0xb7, 0x96, 0x86, 0x2d, 0x4c, 0x30, 0x7d, 0x67, 0x69, 0x58, 0x3e, 0x56,
	0xf4, 0x75, 0x81, 0xd5, 0xe6, 0x7a, 0x9a, 0x5e, 0x14, 0xd8, 0x3f, 0x50, 0x3e, 0x49, 0x3b, 0x8f,
	0x7e, 0x31, 0xa6, 0x48, 0x9b, 0x8d, 0x7e, 0x2d, 0x30, 0x80, 0x62, 0xcf, 0x91, 0x3e, 0xd2, 0x6f,
	0x26, 0x94, 0x35, 0x13, 0xfd, 0x6e, 0x42, 0x49, 0x9d, 0x7e, 0x14, 0xae, 0xf1, 0x6c, 0x16, 0x2e,
	0xbf, 0x52, 0x15, 0x4a, 0x07, 0x38, 0x52, 0xfb, 0xea, 0x9c, 0x92, 0xbe, 0x6d, 0xfe, 0x02, 0x6e,
	0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x11, 0x28, 0x19, 0xd0, 0x8a, 0x06, 0x00, 0x00,
}
